### ISSUE TITLE
The penultimate command of the steps is returning the following error

### ISSUE THREAD

**Issue by uiara** [Melvinsajith/How-to-Install-Mediapipe-in-Jetson-Nano#1]
Tthis is the command

`./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh
`

This is the error

`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/jetson/mediapipe/mediapipe-bin/v0.8.5/numpy-1.19.4-cp36-none-manylinux2014_aarch64.whl'`

**Comment by Melvinsajith** [comment]
Try to run the command in the /mediapipe/mediapipe-bin/  directory by cd into that directory and running this command 

./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh 

try and let me know

**Comment by uiara** [comment]
When trying, I realized that the path that actually exists is this

`./v0.8.5/download.sh
`

In the file that is downloaded first, it does not have this entire path

**Comment by insertuseracct** [comment]
I'm having the same issue

**Comment by Melvinsajith** [comment]
did you install curl using sudo apt install curl, before running the command 

 ./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh

and which jetpack os are you using 
![Screenshot from 2022-03-26 10-32-42](https://user-images.githubusercontent.com/75600365/160225562-2b9b2895-b9e0-4a35-9387-9942a6cd7ad9.png)
[](url)
also make sure  that you are in the mediapipe-bin  directory , some times it may be in the home 
or in the mediapipe directory. 

and run the command inside the mediapipe-bin directory

**Comment by Melvinsajith** [comment]
This error 
![Screenshot from 2022-03-26 10-44-45](https://user-images.githubusercontent.com/75600365/160225801-75116d27-8265-4b3a-a9e5-d96e55592e7a.png)

by running it in the correct directory there will be no error 
![Screenshot from 2022-03-26 10-45-24](https://user-images.githubusercontent.com/75600365/160225913-1121d43c-e4f1-4ccf-8a37-8b8835a204ea.png)

**Comment by insertuseracct** [comment]
![B68B7B07-28EF-4202-A869-FCFA2C396512](https://user-images.githubusercontent.com/102375283/160252327-411fd030-5897-44e9-a9fa-5223edb15577.jpeg)

I’m on Jetpack 4.5
I’ve tried in and out of root and it does the same for both

**Comment by uiara** [comment]
I believe you haven't noticed but the link that is used in step 5 to make the git clone does not offer the same path used.

> ./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh


but yes this is the way that appears there

> ./v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl


I believe you didn't see the error because you must be using an older version of this repository that is already saved in your jetson nano.

If I'm right, could you share this version that is on your jetson nano?

**Comment by uiara** [comment]
Out of curiosity about your experience using the mediapipe on jetson nano, I'm having a hard time reproducing the computer experience on jetson

**Comment by insertuseracct** [comment]
it's jetpack 4.5 but it is in lx mode because it's a 2GB system i believe. not sure how to revert

**Comment by Melvinsajith** [comment]
I have already told in the starting of the video, you should have a newly installed jetpack for installation of mediapipe.

I have been using jetson for the past one year, from my experience 
If we need to install a program like a docker or any thing that affect the system, then we may need to use a newly installed jetpack os or you may get errors that may be only errors for you only , due to version problem.

For example I had installed ROS on my jetson nano and tried  to install mediapipe failed to make it work , after that I need to reinstall new os and first install mediapipe and then install Ros to make it working I think you understood the problem.

So make sure that you are using a newly installed jetpack os

**Comment by insertuseracct** [comment]
It is a fresh install, but on the 2GB nano it instantly goes to the lx edition of ubuntu so I’m not sure if that effecting it

**Comment by Melvinsajith** [comment]
![here-s-the-new-login-screen-of-ubuntu-18-10-cosmic-cuttlefish-using-yaru-theme-522179-4](https://user-images.githubusercontent.com/75600365/160317363-fa584314-75ae-4716-bfd1-200c1020701a.jpg)

you can switch from LX edition, before login in to the jetson if it is available , like in the image

**Comment by insertuseracct** [comment]
I did a fresh install again and ran everything in normal Ubuntu with the same result

**Comment by paulnegz** [comment]
could you post both .whl that you have?
I had to go download the source code from https://github.com/PINTO0309/mediapipe-bin/releases/ to get access to ./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh. This path no longer exist in the zip file as stated by @Uiara . However when I run `sudo pip3 install numpy-1.19.4-cp36-none-manylinux2014_aarch64.whl mediapipe-0.8.5_cuda102-cp36-none-linux_aarch64.whl` I get the file is not a zip file error shown in the picture
![media_nano_error](https://user-images.githubusercontent.com/37233089/161454739-b5ef7812-9191-413b-bc0f-c3b4d1993624.jpg)

**Comment by Melvinsajith** [comment]
> 
are you running this command inside the mediapipe bin directory , make sure you are running the command in the mediapipe bin directory

**Comment by paulnegz** [comment]
Yes, I made sure the commands are run in the mediapipe-bin directory. Could you post both .whl files that you have? The .whl files in the mediapipe-bin right now aren’t the same files as when the video was made. As stated by @Uiara. Or can you upload the mediapipe-bin folder after the download of the.whl files. 
This is running on a newly installed jet pack. 
Try making a new clone of the mediapipe-bin and walking through the tutorial again. The directory is different that's why 3 different people on this thread encountered the same problem.

**Comment by Melvinsajith** [comment]
I understand that the GitHub of mediapipe-bin has changed, I will update it soon in my GitHub also, I have the solution, but need to make sure it is working fine and I will update it in my GitHub. 
so please wait, I will fix it soon

**Comment by Melvinsajith** [comment]
> I believe you haven't noticed but the link that is used in step 5 to make the git clone does not offer the same path used.
> 
> > ./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh
> 
> but yes this is the way that appears there
> 
> > ./v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl
> 
> I believe you didn't see the error because you must be using an older version of this repository that is already saved in your jetson nano.
> 
> If I'm right, could you share this version that is on your jetson nano?

**Comment by Melvinsajith** [comment]
I understand that the GitHub of mediapipe-bin has changed and you guys were getting errors while installing mediapipe , so I have fixed the error and changed the last step in my Github.

so now there should be no error and you can get mediapipe running in the jetson with no problem.

Thank you

**Comment by insertuseracct** [comment]
Retried in regular Ubuntu and still saying no such file or directory
